const assetRoot = '/process-assets'

const asset = (path: string) => `${assetRoot}/${path}`

export const processAssets = {
  backgrounds: {
    historyTimeline: asset('backgrounds/bg-history-timeline.webp'),
    ancientWorkshop: asset('backgrounds/bg-ancient-workshop.webp'),
    preparationTable: asset('backgrounds/bg-preparation-table.webp'),
    steamingStove: asset('backgrounds/bg-steaming-stove.webp'),
    pulpingTable: asset('backgrounds/bg-pulping-table.webp'),
    sheetFormingVat: asset('backgrounds/bg-sheet-forming-vat.webp'),
    dryingYard: asset('backgrounds/bg-drying-yard.webp'),
    dryingWall: asset('backgrounds/bg-drying-wall.webp'),
    cuttingTable: asset('backgrounds/bg-cutting-table.webp'),
    ecoPaperMill: asset('backgrounds/bg-eco-paper-mill.webp'),
    smartPaperFactory: asset('backgrounds/bg-smart-paper-factory.webp'),
    legacyFuture: asset('backgrounds/bg-tradition-to-future.webp'),
  },
  props: {
    oracleBone: asset('props/stage01-oracle-bone.png'),
    bambooSlip: asset('props/stage01-bamboo-slip.png'),
    silkManuscript: asset('props/stage01-silk-scroll.png'),
    xuanPaper: asset('papers/stage01-paper-stack-and-sheets.png'),
    caiLun: asset('props/stage02-cai-lun.png'),
    bark: asset('props/stage02-bark-bundle.png'),
    hemp: asset('props/stage02-hemp-fiber-bundle.png'),
    rag: asset('props/stage02-rag-cloth-pile.png'),
    fishingNet: asset('props/stage02-fishing-net.png'),
    barkCloseup: asset('props/stage03-bamboo-strips.png'),
    ragCloseup: asset('props/stage03-cotton-fiber-ball.png'),
    fishingNetCloseup: asset('props/stage03-separated-fibers.png'),
    waterVat: asset('props/stage03-rectangular-water-vat.png'),
    steamingStove: asset('tools/stage04-stone-stove.png'),
    boilingPot: asset('tools/stage04-boiling-cauldron.png'),
    softenedMaterial: asset('props/stage04-softened-fiber-basket.png'),
    boiledFibers: asset('props/stage04-boiled-fiber-pot.png'),
    materialWhole: asset('props/stage05-fiber-block.png'),
    materialHalfCrushed: asset('props/stage05-crushed-fiber-block.png'),
    paperPulp: asset('props/stage05-pulp-vat.png'),
    pulpWaterSurface: asset('props/stage06-water-vat-top.png'),
    bambooScreenFront: asset('tools/stage06-bamboo-screen-front.png'),
    bambooScreenTilted: asset('tools/stage06-bamboo-screen-tilted.png'),
    attachedFiberMat: asset('papers/stage06-wet-fiber-mat-on-frame.png'),
    bambooRack: asset('tools/stage07-bamboo-drying-rack.png'),
    dryingWallPanel: asset('props/stage07-drying-wall-panel.png'),
    wastePaper: asset('props/stage09-waste-paper-pile.png'),
    shreddedPaper: asset('props/stage09-shredded-paper-pile.png'),
    recycleBin: asset('props/stage09-recycle-bin.png'),
    recycledPaper: asset('papers/stage09-recycled-paper-stack-clean.png'),
    waterTreatmentPool: asset('tools/stage09-water-treatment-pond.png'),
    roboticArm: asset('tools/stage09-robotic-arm.png'),
    greenPaperLine: asset('tools/stage09-greenhouse-paper-line.png'),
    books: asset('props/stage10-book-blue-bound.png'),
    bookDark: asset('props/stage10-book-dark-blue.png'),
    bookKraft: asset('props/stage10-book-kraft-bound.png'),
    calligraphyScroll: asset('papers/stage10-scroll-landscape.png'),
    bambooDecoration: asset('props/stage10-bamboo-decoration.png'),
  },
  tools: {
    cuttingKnife: asset('tools/stage03-cutting-knife.png'),
    woodenBoard: asset('tools/stage03-wooden-work-board.png'),
    mallet: asset('tools/stage05-wooden-mallet.png'),
    mortar: asset('tools/stage05-stone-mortar.png'),
    paperCutter: asset('tools/stage08-paper-cutting-knife.png'),
    woodenTableLarge: asset('tools/stage08-large-wooden-table.png'),
    filterDevice: asset('tools/stage09-water-filter-machine.png'),
  },
  papers: {
    historyStack: asset('papers/stage01-paper-stack-and-sheets.png'),
    framedSheet: asset('papers/stage01-framed-paper-sheet.png'),
    wetLayer: asset('papers/stage06-wet-paper-sheet.png'),
    wetFiberMat: asset('papers/stage06-wet-fiber-mat-on-frame.png'),
    wet: asset('papers/stage07-wet-paper-sheet.png'),
    halfDry: asset('papers/stage07-half-dry-paper-sheet.png'),
    dry: asset('papers/stage07-dry-paper-sheet.png'),
    singleDry: asset('papers/stage08-single-finished-paper.png'),
    stack: asset('papers/stage08-stacked-finished-paper.png'),
    speckledRecycledStack: asset('papers/stage09-recycled-paper-stack-speckled.png'),
    finalStack: asset('papers/stage10-final-paper-stack.png'),
    finalScroll: asset('papers/stage10-rolled-paper-scroll.png'),
    glowSheet: asset('papers/stage10-single-handmade-sheet.png'),
    bambooPainting: asset('papers/stage10-scroll-bamboo-painting.png'),
    plumScroll: asset('papers/stage10-scroll-plum-blossom.png'),
    blankScroll: asset('papers/stage10-scroll-blank.png'),
  },
  effects: {
    inkLandscape: asset('effects/stage10-ink-cloud.png'),
    fire: asset('effects/stage04-fire-flame.png'),
    bubbles: asset('effects/stage04-bubble-large.png'),
    bubbleSmall: asset('effects/stage04-bubble-small.png'),
    steam: asset('effects/stage04-steam-cloud.png'),
    impurityParticles: asset('props/stage04-impurity-twigs.png'),
    fiberParticles: asset('effects/stage05-floating-fibers-a.png'),
    debrisSplash: asset('effects/stage05-pulp-fragments.png'),
    waterSplash: asset('effects/stage05-water-splash.png'),
    floatingFibers: asset('effects/stage06-floating-fiber-petals.png'),
    waterDrops: asset('effects/stage06-water-drops-left.png'),
    waterDropsRight: asset('effects/stage06-water-drops-right.png'),
    waterRipple: asset('effects/stage06-water-ripple-large.png'),
    waterRippleSmall: asset('effects/stage06-water-ripple-small.png'),
    waterRippleSplash: asset('effects/stage06-water-splash-ripple.png'),
    waterWash: asset('effects/stage06-water-wash.png'),
    sunlight: asset('effects/stage07-sunlight-beam.png'),
    dryingSteam: asset('effects/stage07-steam-haze.png'),
    windLines: asset('effects/stage07-wind-streaks-a.png'),
    windLinesB: asset('effects/stage07-wind-streaks-b.png'),
    windLeavesA: asset('effects/stage07-wind-leaves-a.png'),
    windLeavesB: asset('effects/stage07-wind-leaves-b.png'),
    inkSpread: asset('effects/stage10-ink-cloud.png'),
    blueWaterSplash: asset('effects/stage10-blue-water-splash.png'),
  },
  icons: {
    historyMarker: asset('icons/stage08-process-icon-stack.png'),
    materialCard: asset('icons/stage08-process-icon-bamboo.png'),
    fiberDiagram: asset('icons/stage03-bamboo-fiber-diagram.png'),
    processFlow: asset('icons/stage08-process-icon-forming.png'),
    processSoak: asset('icons/stage08-process-icon-soak.png'),
    processDry: asset('icons/stage08-process-icon-sun-dry.png'),
    processStack: asset('icons/stage08-process-icon-stack.png'),
    fiberWeaveDiagram: asset('icons/stage08-fiber-weave-diagram.png'),
    sensorSet: asset('icons/stage09-sensor-leaf.png'),
    sensorThermometer: asset('icons/stage09-sensor-thermometer.png'),
    sensorWifi: asset('icons/stage09-sensor-wifi.png'),
    sensorWater: asset('icons/stage09-sensor-water.png'),
    controlPanel: asset('icons/stage09-control-panel.png'),
  },
} as const
